'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "Funcionalidad para autoguardar My.Settings"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\temp")>  _
        Public ReadOnly Property RutaImagenTemp() As String
            Get
                Return CType(Me("RutaImagenTemp"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\temp")>  _
        Public ReadOnly Property RutaDescargaImagenes() As String
            Get
                Return CType(Me("RutaDescargaImagenes"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property RutaEjecutableScaneo() As String
            Get
                Return CType(Me("RutaEjecutableScaneo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\Program Files\Paint.NET\PaintDotNet.exe")>  _
        Public ReadOnly Property RutaEjecutableRetoque() As String
            Get
                Return CType(Me("RutaEjecutableRetoque"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\IrfanView\i_view32.exe")>  _
        Public ReadOnly Property rutaAplicacionEscaner() As String
            Get
                Return CType(Me("rutaAplicacionEscaner"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\IrfanView\i_view32.ini")>  _
        Public ReadOnly Property pathArchivoConfigEscaner() As String
            Get
                Return CType(Me("pathArchivoConfigEscaner"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7002")>  _
        Public ReadOnly Property codigoEpidemiologia() As String
            Get
                Return CType(Me("codigoEpidemiologia"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=plana01;User ID=novahis;Password=novahis;Unicode=True")>  _
        Public ReadOnly Property cadenaConexionOracle() As String
            Get
                Return CType(Me("cadenaConexionOracle"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property cabeceraBarcodeHistoria() As String
            Get
                Return CType(Me("cabeceraBarcodeHistoria"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7")>  _
        Public ReadOnly Property lenNHCBarcode() As String
            Get
                Return CType(Me("lenNHCBarcode"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("true")>  _
        Public ReadOnly Property barcodeConCabecera() As String
            Get
                Return CType(Me("barcodeConCabecera"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12")>  _
        Public ReadOnly Property longitudBarcode() As String
            Get
                Return CType(Me("longitudBarcode"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("G:\7001")>  _
        Public ReadOnly Property rutaRepositorioHospital() As String
            Get
                Return CType(Me("rutaRepositorioHospital"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("88|229|199|32|241|99|8|181|198|5|67|83|233|80|184|54|116|135|121|107|64|79|248|17"& _ 
            "3|242|4|14|118|88|223|235|151|87|127|227|114|90|136|212|60|64|231|84|207|2|232|1"& _ 
            "|162|79|9|65|132|70|57|25|107|2|15|25|19|225|121|16|115|178|231|92|14|209|231|22"& _ 
            "|140|232|243|194|62|125|171|202|14")>  _
        Public ReadOnly Property cadenaConexion() As String
            Get
                Return CType(Me("cadenaConexion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("12|53|164|203|59|128|58|209|125|126|178|203|152|188|181|125|123|32|167|111|167|84"& _ 
            "|29|253|194|240|205|205|178|136|16|231|19|246|204|71|140|222|120|101|179|91|17|9"& _ 
            "0|69|222|192|97|146|45|91|7|225|202|167|105|128|86|69|208|254|15|108|17|204|62|2"& _ 
            "21|117|108|185|163|86|215|161|147|56|188|192|181|95")>  _
        Public ReadOnly Property direccion() As String
            Get
                Return CType(Me("direccion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("4|133|145|152|252|2|130|93|181|39|76|44|76|34|126|57")>  _
        Public ReadOnly Property fecha() As String
            Get
                Return CType(Me("fecha"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("false")>  _
        Public ReadOnly Property PermitirDigitalizarNoTiff() As String
            Get
                Return CType(Me("PermitirDigitalizarNoTiff"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("false")>  _
        Public ReadOnly Property ModoDepuracion() As String
            Get
                Return CType(Me("ModoDepuracion"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("7018")>  _
        Public Property proyecto() As String
            Get
                Return CType(Me("proyecto"),String)
            End Get
            Set
                Me("proyecto") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UU")>  _
        Public Property PREP_caracter_Usuario() As String
            Get
                Return CType(Me("PREP_caracter_Usuario"),String)
            End Get
            Set
                Me("PREP_caracter_Usuario") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("RX")>  _
        Public Property PREP_caracter_RX() As String
            Get
                Return CType(Me("PREP_caracter_RX"),String)
            End Get
            Set
                Me("PREP_caracter_RX") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("SDSD")>  _
        Public Property PREP_caracter_SinDoc() As String
            Get
                Return CType(Me("PREP_caracter_SinDoc"),String)
            End Get
            Set
                Me("PREP_caracter_SinDoc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CD")>  _
        Public Property PREP_caracter_CD() As String
            Get
                Return CType(Me("PREP_caracter_CD"),String)
            End Get
            Set
                Me("PREP_caracter_CD") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("NDND")>  _
        Public Property PREP_caracter_ND() As String
            Get
                Return CType(Me("PREP_caracter_ND"),String)
            End Get
            Set
                Me("PREP_caracter_ND") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ERROR")>  _
        Public Property PREP_caracter_ERROR() As String
            Get
                Return CType(Me("PREP_caracter_ERROR"),String)
            End Get
            Set
                Me("PREP_caracter_ERROR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DESTRUIR")>  _
        Public Property PREP_caracter_DESTRUIR() As String
            Get
                Return CType(Me("PREP_caracter_DESTRUIR"),String)
            End Get
            Set
                Me("PREP_caracter_DESTRUIR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\buzz.wav")>  _
        Public Property PREP_rutaZumbido() As String
            Get
                Return CType(Me("PREP_rutaZumbido"),String)
            End Get
            Set
                Me("PREP_rutaZumbido") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("C:\SonidoOK.wav")>  _
        Public Property PREP_rutaSonidoOK() As String
            Get
                Return CType(Me("PREP_rutaSonidoOK"),String)
            End Get
            Set
                Me("PREP_rutaSonidoOK") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CICI")>  _
        Public Property PREP_caracter_CI() As String
            Get
                Return CType(Me("PREP_caracter_CI"),String)
            End Get
            Set
                Me("PREP_caracter_CI") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CC")>  _
        Public Property PREP_caracter_Caja() As String
            Get
                Return CType(Me("PREP_caracter_Caja"),String)
            End Get
            Set
                Me("PREP_caracter_Caja") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CL")>  _
        Public Property PREP_caracter_Coleccion() As String
            Get
                Return CType(Me("PREP_caracter_Coleccion"),String)
            End Get
            Set
                Me("PREP_caracter_Coleccion") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("LL")>  _
        Public Property PREP_caracter_Lote() As String
            Get
                Return CType(Me("PREP_caracter_Lote"),String)
            End Get
            Set
                Me("PREP_caracter_Lote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("H;C")>  _
        Public Property PREP_caracter_NHC() As String
            Get
                Return CType(Me("PREP_caracter_NHC"),String)
            End Get
            Set
                Me("PREP_caracter_NHC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TRAZABILIDADLOTES;idLote;UsuarioPreparado;FechaInicioPreparado;FechaFinPreparado")>  _
        Public Property PREP_Tabla_campos() As String
            Get
                Return CType(Me("PREP_Tabla_campos"),String)
            End Get
            Set
                Me("PREP_Tabla_campos") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property cadenaConexionMySQL() As String
            Get
                Return CType(Me("cadenaConexionMySQL"),String)
            End Get
            Set
                Me("cadenaConexionMySQL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("CJ")>  _
        Public Property PREP_caracter_Caja2() As String
            Get
                Return CType(Me("PREP_caracter_Caja2"),String)
            End Get
            Set
                Me("PREP_caracter_Caja2") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DIGI_modificar_NHC() As Boolean
            Get
                Return CType(Me("DIGI_modificar_NHC"),Boolean)
            End Get
            Set
                Me("DIGI_modificar_NHC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("2")>  _
        Public Property DIGI_porcentaje_pixel_negro() As Integer
            Get
                Return CType(Me("DIGI_porcentaje_pixel_negro"),Integer)
            End Get
            Set
                Me("DIGI_porcentaje_pixel_negro") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("c:\TEMP\iScan")>  _
        Public Property DIGI_rutaLocalImagenes() As String
            Get
                Return CType(Me("DIGI_rutaLocalImagenes"),String)
            End Get
            Set
                Me("DIGI_rutaLocalImagenes") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property DIGI_timeout_sin_escanear() As Integer
            Get
                Return CType(Me("DIGI_timeout_sin_escanear"),Integer)
            End Get
            Set
                Me("DIGI_timeout_sin_escanear") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DIGI_TIPOLOTE_modificar() As Boolean
            Get
                Return CType(Me("DIGI_TIPOLOTE_modificar"),Boolean)
            End Get
            Set
                Me("DIGI_TIPOLOTE_modificar") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DIGI_TIPOLOTE_validar_al_cerrar_lote() As Boolean
            Get
                Return CType(Me("DIGI_TIPOLOTE_validar_al_cerrar_lote"),Boolean)
            End Get
            Set
                Me("DIGI_TIPOLOTE_validar_al_cerrar_lote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DIGI_validar_NHC() As Boolean
            Get
                Return CType(Me("DIGI_validar_NHC"),Boolean)
            End Get
            Set
                Me("DIGI_validar_NHC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TPL")>  _
        Public Property PREP_tipoLote() As String
            Get
                Return CType(Me("PREP_tipoLote"),String)
            End Get
            Set
                Me("PREP_tipoLote") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public Property PREP_tipoLote_fijo() As String
            Get
                Return CType(Me("PREP_tipoLote_fijo"),String)
            End Get
            Set
                Me("PREP_tipoLote_fijo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("090")>  _
        Public Property PREP_elimina_prefijo_NHC() As String
            Get
                Return CType(Me("PREP_elimina_prefijo_NHC"),String)
            End Get
            Set
                Me("PREP_elimina_prefijo_NHC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property DIGI_Muestra_Perfiles() As String
            Get
                Return CType(Me("DIGI_Muestra_Perfiles"),String)
            End Get
            Set
                Me("DIGI_Muestra_Perfiles") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public ReadOnly Property separadorCaratula() As Boolean
            Get
                Return CType(Me("separadorCaratula"),Boolean)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("DocumentoClinico")>  _
        Public ReadOnly Property WS_tipoDocumentoATratar() As String
            Get
                Return CType(Me("WS_tipoDocumentoATratar"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("")>  _
        Public ReadOnly Property tipoDocumentoEnUso() As String
            Get
                Return CType(Me("tipoDocumentoEnUso"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.Digitalización.My.MySettings
            Get
                Return Global.Digitalización.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
